---
title: "Gov 50 Final Project"
author: "Jose Valdez Genao"
description: "My final project"
output:
  distill::distill_article:
    self_contained: false
---



## Project thoughts

I am interested in exploring data related to the results of the National Assessments (Pruebas Nacionales) of the Dominican Republic. Every year the Ministry of Education conducts these examinations nationwide, which every student is required to take to graduate from High School. This data is useful to better understand how students are performing in the different subjects (Spanish, Math, Social Sciences, Natural Sciences). Also, exploring this data might tell us how students are performing in the different regions, and the differences in performance between schooling methods (private, public, technical, arts, etc).

## Dataset and Research Question

```{r}
library(readr)
DR_education <- read_csv('Results_PN_Data.csv')
```
Does school performance in the Dominican national assessments correlate with the location, type of schooling, or funding source?

In this project, I aim to investigate potential performance differences in the Dominican national examinations, based on geographical location, school type (e.g., arts, technical, regular), and public or private funding. I hypothesize that students in the capital and metropolitan areas might achieve higher mean scores compared to students in rural areas. Furthermore, I think that there will be significant differences in mean scores across school types. Finally, I expect that students in private schools may exhibit higher mean scores than students in public schools. This hypothesis is grounded in the context of the Dominican Republic's education system, which has faced numerous challenges. From an international perspective, the country ranked in the lowest performance out of 79 participant countries/economies in the international assessment PISA 2018. From a national perspective, my theory is that several factors may contribute to the internal challenges. One of them are the disparities in access to educational resources, particularly in rural areas. For example, there are observed issues related to connectivity, access to electricity, internet, and technology devices. Students are also affected by inadequate infrastructure, lack of lab facilities, high classroom density, and shortages of teachers, which could affect some specific school types more than others. On the other hand, teachers in the capital and metropolitan areas have more access to training in relatively well-funded universities with more experienced faculty. These disparities likely result in variations in students' learning outcomes, contributing to the country's high inequality.

Factual research about these challenges can be found on this reports: 
https://www.thedialogue.org/wp-content/uploads/2013/10/rc_rdom20101.pdf
https://pdf.usaid.gov/pdf_docs/PA00WNWJ.pdf

My sample is in Spanish and includes national examination results from 2016 to 2020. My unit of analysis are the school’s mean results, with 46,283 observations. My first explanatory variable of interest is “Regional” which is measured by assigning every school to 18 different regionals across the country. This variable is coded by assigning each school to a specific region (e.g., School X = 10). Further investigation is needed to classify regions as metropolitan or rural. The second variable, "Nivel/Modalidad" (level/modality), is coded by assigning every school to the type of schooling. These are: General, Academic, Professional Technical, or Arts (e.g., School X = Arts). I plan to code a third variable differentiating between public and private schools, depending on data availability (e.g., School X = Public).

My outcome variables of interest are representing the mean scores in four academic subjects: Español (Spanish), Matemáticas (Math), Sociales (Social Sciences), and Naturales (Natural Sciences). I want to highlight that every academic subject represents a different variable, for a total of four outcome variables. These variables measures scores on a 30% scale, and summarizes the mean scores of all students in a school. For instance, the mean scores of students in School X are coded for Spanish (e.g., Spanish = 16.53).

Support for my hypothesis would be evident if schools in metropolitan areas demonstrate higher mean scores than rural schools. Also, my theory would be supported if there are significant differences across specific school types, or funding source (e.g., Academic or Private), as suggested by my theory. However, my hypothesis would be refuted if the data indicates similar performance across regionals and school types, including no significant difference in performance of public and private schools. Another outcome that would refute my theory is that public schools perform better than private schools. Coding the mean scores (outcome variables) across explanatory variables will allow me to test my hypothesis and draw meaningful conclusions.

